# Minimal allowed log Level.
log-level: info
# Frequency of service dependency calculations (default 24h0m0s)
dependency-storage.data-frequency: 24h0m0s
# Defines which metrics backend to use for metrics reporting: expvar, prometheus, none (default "prometheus")
metrics-backend: none
# Defines the route of HTTP endpoint for metrics backends that support scraping (default "/metrics")
metrics-http-route: /metrics

collector:
  # The http port for the health check service (default 14269)
  health-check-http-port: 14269
  # The http port for the collector service (default 14268)
  http-port: 14268
  # The tchannel port for the collector service (default 14267)
  port: 14267
  # The http port for the Zipkin collector service e.g. 9411
  zipkin.http-port: 9411
  # The number of workers pulling items from the queue (default 50)
  num-workers: 50
  # The queue size of the collector (default 2000)
  queue-size: 2000
  # The duration to wait before rewriting an existing service or operation name (default 12h0m0s)
  write-cache-ttl: 12h0m0s

es:
  # The username required by ElasticSearch
  username: 
  # The password required by ElasticSearch
  password:  
  # The comma-separated list of ElasticSearch servers, must be full url i.e. http://localhost:9200 (default "http://127.0.0.1:9200")
  server-urls: http://elasticsearch-data:9200
  # The maximum lookback for spans in ElasticSearch (default 72h0m0s)
  max-span-age: 1y
  # The number of shards per index in ElasticSearch (default 5)
  num-shards: 3
  # The number of replicas per index in ElasticSearch (default 1)
  num-replicas: 2
  # The sniffer config for ElasticSearch; client uses sniffing process to find all nodes automatically, disable if not required
  sniffer: