# Minimal allowed log Level.
log-level: info
# Frequency of service dependency calculations (default 24h0m0s)
dependency-storage.data-frequency: 24h0m0s
# Defines which metrics backend to use for metrics reporting: expvar, prometheus, none (default "prometheus")
metrics-backend: none
# Defines the route of HTTP endpoint for metrics backends that support scraping (default "/metrics")
metrics-http-route: /metrics

query:
  # The http port for the health check service (default 16687)
  health-check-http-port: 16687
  # The port for the query service (default 16686)
  port: 16686
  # The prefix for the url of the query service (default "api")
  prefix: api
  # The path for the static assets for the UI (default "jaeger-ui-build/build/")
  static-files: /etc/query/jaeger-ui-build/build/
  # The path to the UI configuration file in JSON format
  ui-config: /etc/query/ui-config.json

es:
  # The username required by ElasticSearch
  username: 
  # The password required by ElasticSearch
  password: 
  # The comma-separated list of ElasticSearch servers, must be full url i.e. http://localhost:9200 (default "http://127.0.0.1:9200")
  server-urls: http://elasticsearch-data:9200
  # The maximum lookback for spans in ElasticSearch (default 72h0m0s)
  max-span-age: 1y
  # The number of shards per index in ElasticSearch (default 5)
  num-shards: 3
  # The number of replicas per index in ElasticSearch (default 1)
  num-replicas: 2
  # The sniffer config for ElasticSearch; client uses sniffing process to find all nodes automatically, disable if not required
  sniffer: