git_tag: master
git_repo: 'git@github.com:cloudtrust/keycloak-service.git'

event_emitter_release: https://github.com/cloudtrust/event-emitter/releases/download/v0.1/event_emitter.tar.gz
jaeger_release: https://github.com/cloudtrust/jaeger/releases/download/v1.2.0/v1.2.0.tar.gz  
keycloak_bridge_release: https://github.com/cloudtrust/keycloak-bridge/releases/download/1.0/v1.0.tar.gz
wsfed_release: https://github.com/cloudtrust/keycloak-wsfed/releases/download/3.4.3.Final.0-SNAPSHOT/wsfed-3.4.3.tar.gz
keycloak_export_release: https://github.com/cloudtrust/keycloak-export/releases/download/0.2-SNAPSHOT/keycloak-export.tar.gz

config_repo_name: dev
config_repo: git@github.com:cloudtrust/dev-config.git
config_git_tag: master

server_name: keycloak.cloudtrust.com
